; Stage 0: hand-transliterations of Aeneas pure output into ACL2.
; Sources of truth: tests/lean/Demo/Demo.lean and tests/lean/Loops.lean
; (generated by Aeneas from tests/src/demo.rs and tests/src/loops.rs).
; Recursion uses fuel with measure (nfix fuel); out of fuel is a distinct
; error, exactly as in the Coq backend's fuel mode.

(in-package "ACL2")

(include-book "rust-primitives")

;; ---------------------------------------------------------------------
;; [demo::mul2_add1]:  fn mul2_add1(x: u32) -> u32 { (2 * x) + 1 }
;; Aeneas pure output:  do  let i <- x + x;  i + 1
;; ---------------------------------------------------------------------

(defun demo-mul2-add1 (x)
  (b* (((ok i) (u32-add x x)))
    (u32-add i 1)))

;; [demo::incr]:  fn incr(x: &mut u32) { *x += 1 }
;; &mut argument => first-order: returns the updated value.

(defun demo-incr (x)
  (u32-add x 1))

;; [demo::use_mul2_add1]:  fn use_mul2_add1(x: u32, y: u32) -> u32

(defun demo-use-mul2-add1 (x y)
  (b* (((ok i) (demo-mul2-add1 x)))
    (u32-add i y)))

;; ---------------------------------------------------------------------
;; [demo::CList]:  enum CList<T> { CCons(T, Box<CList<T>>), CNil }
;; Type parameter T erased (untyped ACL2); recursive tagsum via FTY.
;; ---------------------------------------------------------------------

(fty::deftagsum clist
  (:ccons ((hd any-p) (tl clist-p)))
  (:cnil ()))

;; [demo::list_nth]:
;;   fn list_nth<'a, T>(l: &'a CList<T>, i: u32) -> &'a T
;; Aeneas pure output (shared borrow => no backward function):
;;   match l with
;;   | CCons x tl => if i = 0 then ok x else do let i1 <- i - 1; list_nth tl i1
;;   | CNil => fail panic

(defun demo-list-nth (fuel l i)
  (declare (xargs :measure (nfix fuel)))
  (if (zp fuel)
      (fail (err-out-of-fuel))
    (clist-case l
      :ccons (if (eql i 0)
                 (ok (clist-ccons->hd l))
               (b* (((ok i1) (u32-sub i 1)))
                 (demo-list-nth (1- fuel) (clist-ccons->tl l) i1)))
      :cnil (fail (err-failure)))))

;; [demo::i32_id]:  fn i32_id(i: i32) -> i32 { if i == 0 { 0 } else { i32_id(i - 1) + 1 } }

(defun demo-i32-id (fuel n)
  (declare (xargs :measure (nfix fuel)))
  (if (zp fuel)
      (fail (err-out-of-fuel))
    (if (eql n 0)
        (ok 0)
      (b* (((ok n1) (i32-sub n 1))
           ((ok n2) (demo-i32-id (1- fuel) n1)))
        (i32-add n2 1)))))

;; ---------------------------------------------------------------------
;; [loops::sum]:
;;   fn sum(max: u32) -> u32 { let mut i = 0; let mut s = 0;
;;     while i < max { s += i; i += 1; }  s }
;; Aeneas lifts the loop body to a recursive `sum_loop` taking the loop
;; state; the entry function calls it with the initial state.
;; ---------------------------------------------------------------------

(defun loops-sum-loop (fuel max i s)
  (declare (xargs :measure (nfix fuel)))
  (if (zp fuel)
      (fail (err-out-of-fuel))
    (if (< i max)
        (b* (((ok s1) (u32-add s i))
             ((ok i1) (u32-add i 1)))
          (loops-sum-loop (1- fuel) max i1 s1))
      (ok s))))

(defun loops-sum (fuel max)
  (loops-sum-loop fuel max 0 0))

;; Concrete-execution smoke tests (values cross-checked against the Rust
;; sources' own #[test] behavior).
(assert-event (equal (demo-mul2-add1 5) (ok 11)))
(assert-event (equal (demo-mul2-add1 (expt 2 31)) (fail (err-failure))))
(assert-event (equal (demo-use-mul2-add1 3 4) (ok 11)))
(assert-event (equal (demo-i32-id 100 10) (ok 10)))
(assert-event (equal (demo-list-nth 10 (clist-ccons 40 (clist-ccons 50 (clist-cnil))) 1)
                     (ok 50)))
(assert-event (equal (demo-list-nth 10 (clist-ccons 40 (clist-cnil)) 3)
                     (fail (err-failure))))
(assert-event (equal (loops-sum 100 10) (ok 45)))
(assert-event (equal (loops-sum 5 10) (fail (err-out-of-fuel))))
