;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [aes_probe]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

(defconst *aes-probe-sbox* (list 99 124 119 123))

(defun aes-probe-sub (x)
  (b* ((v1_1 (u8-and x 3)))
  (b* (((ok v2_2) (usize-cast v1_1)))
  (array-index *aes-probe-sbox* v2_2))))

(defun aes-probe-xor-into-loop0 (n block k i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n_3 (1- n)))
  (if (< i 4) (b* (((ok v4_4) (array-index k i)))
  (b* (((ok v5_5) (array-index block i)))
  (b* ((v6_6 (u8-xor v5_5 v4_4)))
  (b* (((ok v7_7) (array-update block i v6_6)))
  (b* (((ok i_8) (usize-add i 1)))
  (aes-probe-xor-into-loop0 n_3 v7_7 k i_8)))))) (ok block)))))

(defun aes-probe-xor-into (n block k)
  (aes-probe-xor-into-loop0 n block k 0))

(defun aes-probe-rotl (x n)
  (u32-rotate-left x n))

(defun aes-probe-add-round-key (s k)
  (b* (((ok v9_9) (array-index s 0)))
  (b* (((ok v10_10) (array-index k 0)))
  (b* ((v11_11 (u8-xor v9_9 v10_10)))
  (b* (((ok v12_12) (array-index s 1)))
  (b* (((ok v13_13) (array-index k 1)))
  (b* ((v14_14 (u8-xor v12_12 v13_13)))
  (b* (((ok v15_15) (array-index s 2)))
  (b* (((ok v16_16) (array-index k 2)))
  (b* ((v17_17 (u8-xor v15_15 v16_16)))
  (b* (((ok v18_18) (array-index s 3)))
  (b* (((ok v19_19) (array-index k 3)))
  (b* ((v20_20 (u8-xor v18_18 v19_19)))
  (ok (list v11_11 v14_14 v17_17 v20_20)))))))))))))))

(defun aes-probe-xtime (x)
  (b* (((ok hi_21) (u8-shr x 7)))
  (b* (((ok v22_22) (u8-shl x 1)))
  (b* (((ok v23_23) (u8-mul hi_21 27)))
  (ok (u8-xor v22_22 v23_23))))))

(defun aes-probe-gmul-loop0 (n p a b i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n_24 (1- n)))
  (if (< i 8) (b* ((v25_25 (u8-and b 1)))
  (b* (((ok p_26) (if (equal v25_25 1) (ok (u8-xor p a)) (ok p))))
  (b* (((ok hi_27) (u8-shr a 7)))
  (b* (((ok a_28) (u8-shl a 1)))
  (b* (((ok a_29) (if (equal hi_27 1) (ok (u8-xor a_28 27)) (ok a_28))))
  (b* (((ok b_30) (u8-shr b 1)))
  (b* (((ok i_31) (u32-add i 1)))
  (aes-probe-gmul-loop0 n_24 p_26 a_29 b_30 i_31)))))))) (ok p)))))

(defun aes-probe-gmul (n a b)
  (aes-probe-gmul-loop0 n 0 a b 0))

;; END OF GENERATED FILE
