;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [cast_probe]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

(defun cast-probe-c-u32-u8 (x)
  (u8-cast x))

(defun cast-probe-c-u32-u16 (x)
  (u16-cast x))

(defun cast-probe-c-u8-u32 (x)
  (u32-cast x))

(defun cast-probe-c-u32-i8 (x)
  (i8-cast x))

(defun cast-probe-c-i32-u8 (x)
  (u8-cast x))

;; END OF GENERATED FILE
