;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [demo]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

;; SKIPPED function core-num-u32-wrapping-add: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function core-num-u32-wrapping-sub: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function demo-choose: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

(defun demo-mul2-add1 (x)
  (b* (((ok v0) (u32-add x x)))
  (u32-add v0 1)))

(defun demo-use-mul2-add1 (x y)
  (b* (((ok v0) (demo-mul2-add1 x)))
  (u32-add v0 y)))

(defun demo-incr (x)
  (u32-add x 1))

(defun demo-use-incr ()
  (b* (((ok x) (demo-incr 0)))
  (b* (((ok x) (demo-incr x)))
  (b* (((ok &) (demo-incr x)))
  (ok (unit))))))

(fty::deftagsum demo-clist
  (:ccons ((f0 acl2::any-p) (f1 demo-clist-p)))
  (:cnil ())
  :xvar the-demo-clist)

(defun demo-list-nth (n l i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp1 l))
  (demo-clist-case acl2tmp1
    :ccons (b* ((x (demo-clist-ccons->f0 acl2tmp1)) (tl (demo-clist-ccons->f1 acl2tmp1))) (if (equal i 0) (ok x) (b* (((ok v0) (u32-sub i 1)))
  (demo-list-nth n tl v0))))
    :cnil (fail (err-failure)))))))

(defun demo-list-nth1-loop0 (n l i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp2 l))
  (demo-clist-case acl2tmp2
    :ccons (b* ((x (demo-clist-ccons->f0 acl2tmp2)) (tl (demo-clist-ccons->f1 acl2tmp2))) (if (equal i 0) (ok x) (b* (((ok i) (u32-sub i 1)))
  (demo-list-nth1-loop0 n tl i))))
    :cnil (fail (err-failure)))))))

(defun demo-list-nth1 (n l i)
  (demo-list-nth1-loop0 n l i))

;; SKIPPED function demo-list-nth-mut: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

(defun demo-i32-id (n i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (equal i 0) (ok 0) (b* (((ok v0) (i32-sub i 1)))
  (b* (((ok v0) (demo-i32-id n v0)))
  (i32-add v0 1)))))))

;; SKIPPED function demo-list-tail: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED trait/mixed declaration group (run with --monomorphize)

(defun demo-impl-demo-counter-for-usize-incr (self)
  (b* (((ok self) (usize-add self 1)))
  (ok (cons self self))))

;; SKIPPED trait impl (run with --monomorphize)

;; SKIPPED function demo-use-counter: ACL2: trait method call; run charon with --monomorphize

;; SKIPPED function demo-mod-add: ACL2: call to a function that was itself skipped

;; END OF GENERATED FILE
