;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [itermut_probe]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

;; opaque type core-fmt-arguments (skipped)

(fty::defprod core-iter-adapters-zip-zip
  ((a acl2::any-p) (b acl2::any-p))
  :xvar the-core-iter-adapters-zip-zip)

(fty::defprod core-slice-iter-itermut
  ((lst acl2::any-p) (pos acl2::any-p))
  :xvar the-core-slice-iter-itermut)

(fty::deftagsum core-option-option
  (:none ())
  (:some ((f0 acl2::any-p)))
  :xvar the-core-option-option)

(fty::deftagsum core-panicking-assertkind
  (:eq ())
  (:ne ())
  (:match ())
  :xvar the-core-panicking-assertkind)

(fty::defprod core-slice-iter-iter
  ((lst acl2::any-p) (pos acl2::any-p))
  :xvar the-core-slice-iter-iter)

(defun core-slice-iter-itermut-wb-some (v im)
  (core-slice-iter-itermut (update-nth (- (core-slice-iter-itermut->pos im) 1) v (core-slice-iter-itermut->lst im))
      (- (core-slice-iter-itermut->pos im) 1)))

(defun core-slice-iter-itermut-apply-back (vs im)
  (if (atom vs)
      im
    (core-slice-iter-itermut-apply-back (cdr vs) (core-slice-iter-itermut-wb-some (car vs) im))))

(defun core-iter-adapters-zip-zip-wb-some (v z)
  (core-iter-adapters-zip-zip (core-slice-iter-itermut-wb-some (car v) (core-iter-adapters-zip-zip->a z)) (core-iter-adapters-zip-zip->b z)))

(defun core-iter-adapters-zip-zip-apply-back (vs z)
  (if (atom vs)
      z
    (core-iter-adapters-zip-zip-apply-back (cdr vs) (core-iter-adapters-zip-zip-wb-some (car vs) z))))

(defun core-ops-bit-impl-core-ops-bit-bitxorassign-0-u32-for-u32-bitxor-assign (self other) (ok (u32-xor self other)))

;; SKIPPED trait/mixed declaration group (run with --monomorphize)

;; SKIPPED trait/mixed declaration group (run with --monomorphize)

;; SKIPPED function core-iter-traits-iterator-iterator-zip-core-iter-adapters-zip-zip-core-slice-iter-itermut-mut-: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED trait/mixed declaration group (run with --monomorphize)

(defun core-iter-adapters-zip-impl-core-iter-traits-iterator-iterator-clause0-item-clause1-item-for-core-iter-adapters-zip-zip-a-b-next-core-slice-iter-itermut-mut- (self)
  (b* ((ia (core-iter-adapters-zip-zip->a self))
       (ib (core-iter-adapters-zip-zip->b self))
       (la (core-slice-iter-itermut->lst ia))
       (pa (core-slice-iter-itermut->pos ia))
       (lb (core-slice-iter-iter->lst ib))
       (pb (core-slice-iter-iter->pos ib)))
  (if (and (< pa (len la)) (< pb (len lb)))
      (ok (cons (core-option-option-some (cons (nth pa la) (nth pb lb)))
                (core-iter-adapters-zip-zip (core-slice-iter-itermut la (+ pa 1)) (core-slice-iter-iter lb (+ pb 1)))))
    (ok (cons (core-option-option-none) self)))))

;; SKIPPED function core-iter-traits-iterator-iterator-zip: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function core-iter-traits-iterator-iterator-zip-core-slice-iter-itermut-mut-: ACL2: call to an opaque/std function with no ACL2 mapping yet

(defun core-slice-iter-impl-core-iter-traits-iterator-iterator-a-t-for-core-slice-iter-iter-a-t-next (self)
  (b* ((lst (core-slice-iter-iter->lst self))
       (pos (core-slice-iter-iter->pos self)))
  (if (< pos (len lst))
      (ok (cons (core-option-option-some (nth pos lst)) (core-slice-iter-iter lst (+ pos 1))))
    (ok (cons (core-option-option-none) self)))))

;; SKIPPED trait impl (run with --monomorphize)

(defun core-slice-iter-impl-core-iter-traits-iterator-iterator-core-slice-iter-itermut-mut-a-a-t-for-t-next (self)
  (b* ((lst (core-slice-iter-itermut->lst self))
       (pos (core-slice-iter-itermut->pos self)))
  (if (< pos (len lst))
      (ok (cons (core-option-option-some (nth pos lst)) (core-slice-iter-itermut lst (+ pos 1))))
    (ok (cons (core-option-option-none) self)))))

;; SKIPPED trait impl (run with --monomorphize)

(defun core-slice-iter-impl-core-iter-traits-collect-intoiterator-a-t-core-slice-iter-iter-a-t-for-a-t-into-iter (self) (ok (core-slice-iter-iter self 0)))

;; SKIPPED trait impl (run with --monomorphize)

(defun core-slice-t-iter (self) (ok (core-slice-iter-iter self 0)))

;; SKIPPED function core-slice-t-iter-mut: ACL2: call to an opaque/std function with no ACL2 mapping yet

(defun itermut-probe-p1-iter-sum-loop0 (n iter s)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_1 (1- n)))
  (b* (((ok v2_2) (core-slice-iter-impl-core-iter-traits-iterator-iterator-a-t-for-core-slice-iter-iter-a-t-next iter)))
  (b* ((acl2tmp3 v2_2)
     (v4_4 (car acl2tmp3))
     (iter_5 (cdr acl2tmp3)))
  (b* ((acl2tmp6 v4_4))
  (core-option-option-case acl2tmp6
    :none (ok s)
    :some (b* ((x_7 (core-option-option-some->f0 acl2tmp6))) (b* (((ok s_8) (u32-wrapping-add s x_7)))
  (itermut-probe-p1-iter-sum-loop0 n_1 iter_5 s_8))))))))))

(defun itermut-probe-p1-iter-sum (n xs)
  (b* (((ok iter_9) (core-slice-t-iter xs)))
  (itermut-probe-p1-iter-sum-loop0 n iter_9 0)))

(defun itermut-probe-p2-itermut-inc-loop0 (n iter back)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_10 (1- n)))
  (b* (((ok v11_11) (core-slice-iter-impl-core-iter-traits-iterator-iterator-core-slice-iter-itermut-mut-a-a-t-for-t-next iter)))
  (b* ((v12_12 (car v11_11))
     (iter_13 (cdr v11_11)))
  (b* ((acl2tmp15 v12_12))
  (core-option-option-case acl2tmp15
    :none (ok (b* ((v16_16 iter_13))
  (core-slice-iter-itermut-apply-back back v16_16)))
    :some (b* ((x_17 (core-option-option-some->f0 acl2tmp15))) (b* (((ok x_18) (u32-wrapping-add x_17 1)))
  (itermut-probe-p2-itermut-inc-loop0 n_10 iter_13 (cons x_18 back)))))))))))

(defun itermut-probe-p2-itermut-inc (n xs)
  (b* ((acl2tmp21 (core-slice-iter-itermut xs 0)))
  (b* ((iter_23 acl2tmp21))
  (b* (((ok back_26) (itermut-probe-p2-itermut-inc-loop0 n iter_23 nil)))
  (ok (core-slice-iter-itermut->lst back_26))))))

(defun itermut-probe-p3-zip-xor-loop0 (n iter back)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_27 (1- n)))
  (b* (((ok v28_28) (core-iter-adapters-zip-impl-core-iter-traits-iterator-iterator-clause0-item-clause1-item-for-core-iter-adapters-zip-zip-a-b-next-core-slice-iter-itermut-mut- iter)))
  (b* ((v29_29 (car v28_28))
     (iter_30 (cdr v28_28)))
  (b* ((acl2tmp32 v29_29))
  (core-option-option-case acl2tmp32
    :none (ok (b* ((v33_33 iter_30))
  (core-iter-adapters-zip-zip-apply-back back v33_33)))
    :some (b* ((v34_34 (core-option-option-some->f0 acl2tmp32))) (b* ((acl2tmp35 v34_34)
     (x_36 (car acl2tmp35))
     (y_37 (cdr acl2tmp35)))
  (b* (((ok x_38) (core-ops-bit-impl-core-ops-bit-bitxorassign-0-u32-for-u32-bitxor-assign x_36 y_37)))
  (itermut-probe-p3-zip-xor-loop0 n_27 iter_30 (cons (cons x_38 y_37) back))))))))))))

(defun itermut-probe-p3-zip-xor (n a b)
  (b* ((acl2tmp41 (core-slice-iter-itermut a 0)))
  (b* ((v43_43 acl2tmp41))
  (b* ((acl2tmp45 (core-iter-adapters-zip-zip v43_43 (core-slice-iter-iter b 0))))
  (b* ((iter_47 acl2tmp45))
  (b* (((ok back_50) (itermut-probe-p3-zip-xor-loop0 n iter_47 nil)))
  (b* ((v51_51 (core-iter-adapters-zip-zip->a back_50)))
  (ok (core-slice-iter-itermut->lst v51_51)))))))))

(defun itermut-probe-p4-ark-exact-loop0 (n iter back)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_52 (1- n)))
  (b* (((ok v53_53) (core-iter-adapters-zip-impl-core-iter-traits-iterator-iterator-clause0-item-clause1-item-for-core-iter-adapters-zip-zip-a-b-next-core-slice-iter-itermut-mut- iter)))
  (b* ((v54_54 (car v53_53))
     (iter_55 (cdr v53_53)))
  (b* ((acl2tmp57 v54_54))
  (core-option-option-case acl2tmp57
    :none (ok (b* ((v58_58 iter_55))
  (core-iter-adapters-zip-zip-apply-back back v58_58)))
    :some (b* ((v59_59 (core-option-option-some->f0 acl2tmp57))) (b* ((acl2tmp60 v59_59)
     (a_61 (car acl2tmp60))
     (b_62 (cdr acl2tmp60)))
  (b* (((ok a_63) (core-ops-bit-impl-core-ops-bit-bitxorassign-0-u32-for-u32-bitxor-assign a_61 b_62)))
  (itermut-probe-p4-ark-exact-loop0 n_52 iter_55 (cons (cons a_63 b_62) back))))))))))))

(defun itermut-probe-p4-ark-exact (n state-var rkey)
  (b* (((ok left-val_66) (vec-len rkey)))
  (b* (((ok &) (massert (equal left-val_66 8))))
  (b* ((v67_67 state-var))
  (b* ((acl2tmp69 (core-slice-iter-itermut v67_67 0)))
  (b* ((v71_71 acl2tmp69))
  (b* ((acl2tmp73 (core-iter-adapters-zip-zip v71_71 (core-slice-iter-iter rkey 0))))
  (b* ((iter_75 acl2tmp73))
  (b* (((ok back_78) (itermut-probe-p4-ark-exact-loop0 n iter_75 nil)))
  (b* ((v79_79 (core-iter-adapters-zip-zip->a back_78)))
  (b* ((v80_80 (core-slice-iter-itermut->lst v79_79)))
  (ok v80_80))))))))))))

(defun itermut-probe-driver (n)
  (b* ((v81_81 (list 1 2 3 4 5 6 7 8)))
  (b* (((ok v83_83) (itermut-probe-p2-itermut-inc n v81_81)))
  (b* ((st_84 v83_83))
  (b* ((v85_85 st_84))
  (b* ((v87_87 (list 8 7 6 5 4 3 2 1)))
  (b* (((ok v88_88) (itermut-probe-p3-zip-xor n v85_85 v87_87)))
  (b* ((st_89 v88_88))
  (b* ((v90_90 (list 8 7 6 5 4 3 2 1)))
  (b* (((ok st_91) (itermut-probe-p4-ark-exact n st_89 v90_90)))
  (b* ((v92_92 st_91))
  (itermut-probe-p1-iter-sum n v92_92))))))))))))

;; END OF GENERATED FILE
