;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [lebytes_probe]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

;; opaque type core-array-tryfromsliceerror (skipped)

(fty::defprod core-ops-range-range-usize-
  ((start acl2::any-p) (end acl2::any-p))
  :xvar the-core-ops-range-range-usize-)

(fty::deftagsum core-result-result-u8-4usize-core-array-tryfromsliceerror-
  (:ok ((f0 acl2::any-p)))
  (:err ((f0 acl2::any-p)))
  :xvar the-core-result-result-u8-4usize-core-array-tryfromsliceerror-)

(defun core-array-impl-core-ops-index-index-core-ops-range-range-usize-for-u8-8usize-index-u8-core-ops-range-range-usize-8usize- (self r) (vec-index-range self (core-ops-range-range-usize-->start r) (core-ops-range-range-usize-->end r)))

;; SKIPPED function core-array-impl-core-ops-index-indexmut-core-ops-range-range-usize-for-u8-8usize-index-mut-u8-core-ops-range-range-usize-8usize-: ACL2: call to an opaque/std function with no ACL2 mapping yet

(defun core-convert-impl-core-convert-tryinto-u8-4usize-for-u8-try-into-u8-u8-4usize- (self)
  (if (equal (len self) 4)
      (ok (core-result-result-u8-4usize-core-array-tryfromsliceerror--ok self))
    (ok (core-result-result-u8-4usize-core-array-tryfromsliceerror--err (unit)))))

(defun core-result-core-result-result-u8-4usize-core-array-tryfromsliceerror-unwrap-u8-4usize-core-array-tryfromsliceerror- (self)
  (if (eq (core-result-result-u8-4usize-core-array-tryfromsliceerror--kind self) :ok)
      (ok (core-result-result-u8-4usize-core-array-tryfromsliceerror--ok->f0 self))
    (result-fail (err-failure))))

(defun lebytes-probe-ld (x)
  (b* (((ok v1_1) (core-array-impl-core-ops-index-index-core-ops-range-range-usize-for-u8-8usize-index-u8-core-ops-range-range-usize-8usize- x (make-core-ops-range-range-usize- :start 2 :end 6))))
  (b* (((ok v2_2) (core-convert-impl-core-convert-tryinto-u8-4usize-for-u8-try-into-u8-u8-4usize- v1_1)))
  (b* (((ok v3_3) (core-result-core-result-result-u8-4usize-core-array-tryfromsliceerror-unwrap-u8-4usize-core-array-tryfromsliceerror- v2_2)))
  (ok (u32-from-le-bytes v3_3))))))

(defun lebytes-probe-st (w)
  (b* ((out_4 (array-repeat 8 0)))
  (b* ((acl2tmp5 out_4)
     (acl2tmp6 (make-core-ops-range-range-usize- :start 2 :end 6))
     ((ok acl2tmp7) (vec-index-range acl2tmp5 (core-ops-range-range-usize-->start acl2tmp6) (core-ops-range-range-usize-->end acl2tmp6))))
  (b* ((v9_9 acl2tmp7))
  (b* ((v11_11 (u32-to-le-bytes w)))
  (b* ((v12_12 v11_11))
  (b* (((ok v13_13) (slice-copy-from-slice v9_9 v12_12)))
  (ok (vec-update-range acl2tmp5 (core-ops-range-range-usize-->start acl2tmp6) (core-ops-range-range-usize-->end acl2tmp6) v13_13)))))))))

(defun lebytes-probe-st2 (w)
  (b* ((v14_14 (array-repeat 8 0)))
  (b* ((out_15 (array-repeat 2 v14_14)))
  (b* ((acl2tmp16 out_15)
     (acl2tmp17 1)
     ((ok acl2tmp18) (array-index acl2tmp16 acl2tmp17)))
  (b* ((v20_20 acl2tmp18))
  (b* ((acl2tmp22 v20_20)
     (acl2tmp23 (make-core-ops-range-range-usize- :start 2 :end 6))
     ((ok acl2tmp24) (vec-index-range acl2tmp22 (core-ops-range-range-usize-->start acl2tmp23) (core-ops-range-range-usize-->end acl2tmp23))))
  (b* ((v26_26 acl2tmp24))
  (b* ((v28_28 (u32-to-le-bytes w)))
  (b* ((v29_29 v28_28))
  (b* (((ok v30_30) (slice-copy-from-slice v26_26 v29_29)))
  (b* ((v31_31 (vec-update-range acl2tmp22 (core-ops-range-range-usize-->start acl2tmp23) (core-ops-range-range-usize-->end acl2tmp23) v30_30)))
  (ok (update-nth acl2tmp17 v31_31 acl2tmp16)))))))))))))

;; END OF GENERATED FILE
