;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [loop_break]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

(defun loop-break-step-a (s k)
  (b* (((ok i_1) (usize-rem k 4)))
  (b* (((ok x_2) (array-index s i_1)))
  (b* (((ok v3_3) (u32-wrapping-add x_2 1)))
  (array-update s i_1 v3_3)))))

(defun loop-break-step-b (s k)
  (b* (((ok i_4) (usize-rem k 4)))
  (b* (((ok x_5) (array-index s i_4)))
  (b* (((ok v6_6) (u32-wrapping-add x_5 1)))
  (array-update s i_4 v6_6)))))

(defun loop-break-run-loop0 (n s k)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_7 (1- n)))
  (b* (((ok s_8) (loop-break-step-a s k)))
  (b* (((ok k_9) (usize-add k 1)))
  (if (equal k_9 8) (ok s_8) (b* (((ok s_10) (loop-break-step-b s_8 k_9)))
  (b* (((ok k_11) (usize-add k_9 1)))
  (loop-break-run-loop0 n_7 s_10 k_11)))))))))

(defun loop-break-run (n s)
  (loop-break-run-loop0 n s 1))

;; END OF GENERATED FILE
