;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [loops]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

(fty::deftagsum core-option-option
  (:none ())
  (:some ((f0 acl2::any-p)))
  :xvar the-core-option-option)

;; SKIPPED trait/mixed declaration group (run with --monomorphize)

;; SKIPPED trait impl (run with --monomorphize)

;; SKIPPED trait/mixed declaration group (run with --monomorphize)

;; SKIPPED function core-slice-index-impl-core-slice-index-sliceindex-t-t-for-usize-index-mut: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function core-slice-index-impl-core-slice-index-sliceindex-t-t-for-usize-index: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function core-slice-index-impl-core-slice-index-sliceindex-t-t-for-usize-get-unchecked-mut: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function core-slice-index-impl-core-slice-index-sliceindex-t-t-for-usize-get-unchecked: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function core-slice-index-impl-core-slice-index-sliceindex-t-t-for-usize-get-mut: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function core-slice-index-impl-core-slice-index-sliceindex-t-t-for-usize-get: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED trait impl (run with --monomorphize)

;; SKIPPED function core-slice-t-len: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; unit struct alloc-alloc-global (values are (unit))

;; opaque type alloc-vec-vec (skipped)

(defun loops-iter-loop0 (n max i)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_1 (1- n)))
  (if (< i max) (b* (((ok i_2) (u32-add i 1)))
  (loops-iter-loop0 n_1 max i_2)) (ok i)))))

(defun loops-iter (n max)
  (loops-iter-loop0 n max 0))

(defun loops-sum-loop0 (n max i s)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_3 (1- n)))
  (if (< i max) (b* (((ok s_4) (u32-add s i)))
  (b* (((ok i_5) (u32-add i 1)))
  (loops-sum-loop0 n_3 max i_5 s_4))) (ok s)))))

(defun loops-sum (n max)
  (b* (((ok s_6) (loops-sum-loop0 n max 0 0)))
  (u32-mul s_6 2)))

(defun loops-sum-with-mut-borrows-loop0 (n max i s)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_7 (1- n)))
  (if (< i max) (b* (((ok ms_8) (u32-add s i)))
  (b* (((ok mi_9) (u32-add i 1)))
  (loops-sum-with-mut-borrows-loop0 n_7 max mi_9 ms_8))) (ok s)))))

(defun loops-sum-with-mut-borrows (n max)
  (b* (((ok s_10) (loops-sum-with-mut-borrows-loop0 n max 0 0)))
  (u32-mul s_10 2)))

(defun loops-sum-with-shared-borrows-loop0 (n max i s)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_11 (1- n)))
  (if (< i max) (b* (((ok i_12) (u32-add i 1)))
  (b* (((ok s_13) (u32-add s i_12)))
  (loops-sum-with-shared-borrows-loop0 n_11 max i_12 s_13))) (ok s)))))

(defun loops-sum-with-shared-borrows (n max)
  (b* (((ok s_14) (loops-sum-with-shared-borrows-loop0 n max 0 0)))
  (u32-mul s_14 2)))

;; SKIPPED function loops-sum-array: ACL2: const generics not supported yet

;; SKIPPED function loops-sum-array: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-clear: ACL2: application of a function-typed variable (HO)

;; SKIPPED function loops-clear: ACL2: call to a function that was itself skipped

(fty::deftagsum loops-list
  (:cons ((f0 acl2::any-p) (f1 loops-list-p)))
  (:nil ())
  :xvar the-loops-list)

(defun loops-list-mem-loop0 (n x ls)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_25 (1- n)))
  (b* ((acl2tmp26 ls))
  (loops-list-case acl2tmp26
    :cons (b* ((y_27 (loops-list-cons->f0 acl2tmp26)) (tl_28 (loops-list-cons->f1 acl2tmp26))) (if (equal y_27 x) (ok t) (loops-list-mem-loop0 n_25 x tl_28)))
    :nil (ok nil))))))

(defun loops-list-mem (n x ls)
  (loops-list-mem-loop0 n x ls))

;; SKIPPED function loops-list-nth-mut: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED function loops-list-nth-mut: ACL2: call to a function that was itself skipped

(defun loops-list-nth-shared-loop0 (n ls i)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_38 (1- n)))
  (b* ((acl2tmp39 ls))
  (loops-list-case acl2tmp39
    :cons (b* ((x_40 (loops-list-cons->f0 acl2tmp39)) (tl_41 (loops-list-cons->f1 acl2tmp39))) (if (equal i 0) (ok x_40) (b* (((ok i_42) (u32-sub i 1)))
  (loops-list-nth-shared-loop0 n_38 tl_41 i_42))))
    :nil (result-fail (err-failure)))))))

(defun loops-list-nth-shared (n ls i)
  (loops-list-nth-shared-loop0 n ls i))

;; SKIPPED function loops-get-elem-mut: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED function loops-get-elem-mut: ACL2: call to a function that was itself skipped

(defun loops-get-elem-shared-loop0 (n x ls)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_55 (1- n)))
  (b* ((acl2tmp56 ls))
  (loops-list-case acl2tmp56
    :cons (b* ((y_57 (loops-list-cons->f0 acl2tmp56)) (tl_58 (loops-list-cons->f1 acl2tmp56))) (if (equal y_57 x) (ok y_57) (loops-get-elem-shared-loop0 n_55 x tl_58)))
    :nil (result-fail (err-failure)))))))

(defun loops-get-elem-shared (n slots x)
  (b* (((ok ls_59) (array-index slots 0)))
  (loops-get-elem-shared-loop0 n x ls_59)))

;; SKIPPED function loops-id-mut: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

(defun loops-id-shared (ls)
  (ok ls))

;; SKIPPED function loops-list-nth-mut-with-id: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED function loops-list-nth-mut-with-id: ACL2: call to a function that was itself skipped

(defun loops-list-nth-shared-with-id-loop0 (n i ls)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_69 (1- n)))
  (b* ((acl2tmp70 ls))
  (loops-list-case acl2tmp70
    :cons (b* ((x_71 (loops-list-cons->f0 acl2tmp70)) (tl_72 (loops-list-cons->f1 acl2tmp70))) (if (equal i 0) (ok x_71) (b* (((ok i_73) (u32-sub i 1)))
  (loops-list-nth-shared-with-id-loop0 n_69 i_73 tl_72))))
    :nil (result-fail (err-failure)))))))

(defun loops-list-nth-shared-with-id (n ls i)
  (b* (((ok ls_74) (loops-id-shared ls)))
  (loops-list-nth-shared-with-id-loop0 n i ls_74)))

;; SKIPPED function loops-list-nth-mut-pair: ACL2: destructuring let arity <> 2

;; SKIPPED function loops-list-nth-mut-pair: ACL2: call to a function that was itself skipped

(defun loops-list-nth-shared-pair-loop0 (n ls0 ls1 i)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_89 (1- n)))
  (b* ((acl2tmp90 ls0))
  (loops-list-case acl2tmp90
    :cons (b* ((x0_91 (loops-list-cons->f0 acl2tmp90)) (tl0_92 (loops-list-cons->f1 acl2tmp90))) (b* ((acl2tmp93 ls1))
  (loops-list-case acl2tmp93
    :cons (b* ((x1_94 (loops-list-cons->f0 acl2tmp93)) (tl1_95 (loops-list-cons->f1 acl2tmp93))) (if (equal i 0) (ok (cons x0_91 x1_94)) (b* (((ok i_96) (u32-sub i 1)))
  (loops-list-nth-shared-pair-loop0 n_89 tl0_92 tl1_95 i_96))))
    :nil (result-fail (err-failure)))))
    :nil (result-fail (err-failure)))))))

(defun loops-list-nth-shared-pair (n ls0 ls1 i)
  (loops-list-nth-shared-pair-loop0 n ls0 ls1 i))

;; SKIPPED function loops-list-nth-mut-pair-merge: ACL2: destructuring let arity <> 2

;; SKIPPED function loops-list-nth-mut-pair-merge: ACL2: call to a function that was itself skipped

(defun loops-list-nth-shared-pair-merge-loop0 (n ls0 ls1 i)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_111 (1- n)))
  (b* ((acl2tmp112 ls0))
  (loops-list-case acl2tmp112
    :cons (b* ((x0_113 (loops-list-cons->f0 acl2tmp112)) (tl0_114 (loops-list-cons->f1 acl2tmp112))) (b* ((acl2tmp115 ls1))
  (loops-list-case acl2tmp115
    :cons (b* ((x1_116 (loops-list-cons->f0 acl2tmp115)) (tl1_117 (loops-list-cons->f1 acl2tmp115))) (if (equal i 0) (ok (cons x0_113 x1_116)) (b* (((ok i_118) (u32-sub i 1)))
  (loops-list-nth-shared-pair-merge-loop0 n_111 tl0_114 tl1_117 i_118))))
    :nil (result-fail (err-failure)))))
    :nil (result-fail (err-failure)))))))

(defun loops-list-nth-shared-pair-merge (n ls0 ls1 i)
  (loops-list-nth-shared-pair-merge-loop0 n ls0 ls1 i))

;; SKIPPED function loops-list-nth-mut-shared-pair: ACL2: destructuring let arity <> 2

;; SKIPPED function loops-list-nth-mut-shared-pair: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-list-nth-mut-shared-pair-merge: ACL2: destructuring let arity <> 2

;; SKIPPED function loops-list-nth-mut-shared-pair-merge: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-list-nth-shared-mut-pair: ACL2: destructuring let arity <> 2

;; SKIPPED function loops-list-nth-shared-mut-pair: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-list-nth-shared-mut-pair-merge: ACL2: destructuring let arity <> 2

;; SKIPPED function loops-list-nth-shared-mut-pair-merge: ACL2: call to a function that was itself skipped

(defun loops-ignore-input-mut-borrow-loop0 (n i)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_171 (1- n)))
  (if (> i 0) (b* (((ok i_172) (u32-sub i 1)))
  (loops-ignore-input-mut-borrow-loop0 n_171 i_172)) (ok (unit))))))

(defun loops-ignore-input-mut-borrow (n -a i)
  (b* (((ok &) (loops-ignore-input-mut-borrow-loop0 n i)))
  (ok -a)))

(defun loops-incr-ignore-input-mut-borrow-loop0 (n i)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_173 (1- n)))
  (if (> i 0) (b* (((ok i_174) (u32-sub i 1)))
  (loops-incr-ignore-input-mut-borrow-loop0 n_173 i_174)) (ok (unit))))))

(defun loops-incr-ignore-input-mut-borrow (n a i)
  (b* (((ok a_175) (u32-add a 1)))
  (b* (((ok &) (loops-incr-ignore-input-mut-borrow-loop0 n i)))
  (ok a_175))))

(defun loops-ignore-input-shared-borrow-loop0 (n i)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_176 (1- n)))
  (if (> i 0) (b* (((ok i_177) (u32-sub i 1)))
  (loops-ignore-input-shared-borrow-loop0 n_176 i_177)) (ok (unit))))))

(defun loops-ignore-input-shared-borrow (n -a i)
  (b* (((ok &) (loops-ignore-input-shared-borrow-loop0 n i)))
  (ok -a)))

(defun loops-issue500-1-bar (-a)
  (ok -a))

(defun loops-issue500-1-loop0 (n a)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_178 (1- n)))
  (if (< 0 0) (b* (((ok a_179) (loops-issue500-1-bar a)))
  (loops-issue500-1-loop0 n_178 a_179)) (ok a)))))

(defun loops-issue500-1 (n s)
  (loops-issue500-1-loop0 n s))

(defun loops-issue500-2-bar (-a)
  (ok -a))

(fty::defprod loops-issue500-2-a
  ((f0 acl2::any-p))
  :xvar the-loops-issue500-2-a)

(defun loops-issue500-2-loop0 (n)
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_180 (1- n)))
  (ok (unit)))))

(defun loops-issue500-2 (n s)
  (b* (((ok &) (loops-issue500-2-loop0 n)))
  (ok s)))

(fty::defprod loops-issue500-3-a
  ((f0 acl2::any-p))
  :xvar the-loops-issue500-3-a)

(defun loops-issue500-3-loop0 (n)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_181 (1- n)))
  (if (< 0 0) (loops-issue500-3-loop0 n_181) (ok (unit))))))

(defun loops-issue500-3 (n s)
  (b* (((ok &) (loops-issue500-3-loop0 n)))
  (ok s)))

(defun loops-issue351-loop0 (n t-var last)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_182 (1- n)))
  (b* ((acl2tmp183 t-var))
  (loops-list-case acl2tmp183
    :cons (b* ((ht_184 (loops-list-cons->f0 acl2tmp183)) (tt_185 (loops-list-cons->f1 acl2tmp183))) (loops-issue351-loop0 n_182 tt_185 ht_184))
    :nil (ok last))))))

(defun loops-issue351 (n h t-var)
  (loops-issue351-loop0 n t-var h))

(defun loops-issue270-box-get-borrow (x)
  (ok x))

(defun loops-issue270-loop0 (n t-var last)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_186 (1- n)))
  (b* ((acl2tmp187 t-var))
  (loops-list-case acl2tmp187
    :cons (b* ((ht_188 (loops-list-cons->f0 acl2tmp187)) (tt_189 (loops-list-cons->f1 acl2tmp187))) (b* (((ok t-var_190) (loops-issue270-box-get-borrow tt_189)))
  (loops-issue270-loop0 n_186 t-var_190 ht_188)))
    :nil (ok last))))))

(defun loops-issue270 (n v)
  (b* ((acl2tmp191 v))
  (loops-list-case acl2tmp191
    :cons (b* ((h_192 (loops-list-cons->f0 acl2tmp191)) (t-var_193 (loops-list-cons->f1 acl2tmp191))) (b* (((ok t-var_194) (loops-issue270-box-get-borrow t-var_193)))
  (b* (((ok last_195) (loops-issue270-loop0 n t-var_194 h_192)))
  (ok (core-option-option-some last_195)))))
    :nil (ok (core-option-option-none)))))

;; SKIPPED function loops-issue400-1: ACL2: application of a function-typed variable (HO)

;; SKIPPED function loops-issue400-1: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED function loops-issue400-2: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-issue400-2: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

(defconst *loops-copy-carray-carray* (list 0 1))

(defun loops-copy-carray-loop0 (n a i)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_198 (1- n)))
  (if (< i 2) (b* (((ok v199_199) (array-index *loops-copy-carray-carray* i)))
  (b* (((ok v200_200) (array-update a i v199_199)))
  (b* (((ok i_201) (usize-add i 1)))
  (loops-copy-carray-loop0 n_198 v200_200 i_201)))) (ok a)))))

(defun loops-copy-carray (n a)
  (loops-copy-carray-loop0 n a 0))

(defun loops-iter-local-mut-borrow-loop0 (n p)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_202 (1- n)))
  (b* (((ok p_203) (i32-add p 1)))
  (if (equal p_203 10) (ok (unit)) (loops-iter-local-mut-borrow-loop0 n_202 p_203))))))

(defun loops-iter-local-mut-borrow (n)
  (loops-iter-local-mut-borrow-loop0 n 0))

(defun loops-iter-local-shared-borrow-loop0 (n)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_204 (1- n)))
  (if (equal 0 0) (ok (unit)) (loops-iter-local-shared-borrow-loop0 n_204)))))

(defun loops-iter-local-shared-borrow (n)
  (loops-iter-local-shared-borrow-loop0 n))

(fty::deftagsum loops-alist
  (:cons ((f0 acl2::any-p) (f1 acl2::any-p) (f2 loops-alist-p)))
  (:nil ())
  :xvar the-loops-alist)

(defun loops-insert-in-list-loop0 (n key value ls)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_205 (1- n)))
  (b* ((acl2tmp206 ls))
  (loops-alist-case acl2tmp206
    :cons (b* ((ckey_207 (loops-alist-cons->f0 acl2tmp206)) (cvalue_208 (loops-alist-cons->f1 acl2tmp206)) (tl_209 (loops-alist-cons->f2 acl2tmp206))) (if (equal ckey_207 key) (ok (cons nil (loops-alist-cons ckey_207 value tl_209))) (b* (((ok v210_210) (loops-insert-in-list-loop0 n_205 key value tl_209)))
  (b* ((acl2tmp211 v210_210)
     (v212_212 (car acl2tmp211))
     (back_213 (cdr acl2tmp211)))
  (b* ((back_214 (loops-alist-cons ckey_207 cvalue_208 back_213)))
  (ok (cons v212_212 back_214)))))))
    :nil (ok (cons t (loops-alist-cons key value (loops-alist-nil)))))))))

(defun loops-insert-in-list (n key value ls)
  (loops-insert-in-list-loop0 n key value ls))

(defun loops-reborrow-const-reborrow (x)
  (ok x))

(defun loops-reborrow-const-loop0 (n)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_215 (1- n)))
  (if (< 0 5) (b* (((ok &) (loops-reborrow-const-reborrow 0)))
  (loops-reborrow-const-loop0 n_215)) (ok (unit))))))

(defun loops-reborrow-const (n)
  (loops-reborrow-const-loop0 n))

(defun loops-decode-loop1 (n dst-coeff)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_216 (1- n)))
  (if (> dst-coeff 32) (loops-decode-loop1 n_216 dst-coeff) (ok (unit))))))

;; SKIPPED function loops-decode: ACL2: &mut index survived to extraction (backward function)

;; SKIPPED function loops-decode: ACL2: call to a function that was itself skipped

(defun loops-as-radix-minimized-loop0 (n scalar i)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_218 (1- n)))
  (if (< i 4) (b* (((ok &) (if (equal i 0) (b* (((ok v222_222) (array-index scalar i)))
  (u64-shr v222_222 1)) (b* (((ok v219_219) (array-index scalar i)))
  (b* (((ok v220_220) (u64-shr v219_219 1)))
  (b* (((ok v221_221) (u64-shl v219_219 63)))
  (ok (u64-or v220_220 v221_221))))))))
  (b* (((ok i_223) (usize-add i 1)))
  (loops-as-radix-minimized-loop0 n_218 scalar i_223))) (ok (unit))))))

(defun loops-as-radix-minimized (n)
  (b* ((scalar_224 (array-repeat 4 0)))
  (loops-as-radix-minimized-loop0 n scalar_224 0)))

(defun loops-single-break-loop0 (n d)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_225 (1- n)))
  (b* (((ok v226_226) (array-index d 0)))
  (if (equal v226_226 0) (ok (unit)) (loops-single-break-loop0 n_225 d))))))

(defun loops-single-break (n d)
  (loops-single-break-loop0 n d))

;; END OF GENERATED FILE
