;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [loops]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

(fty::deftagsum core-option-option
  (:none ())
  (:some ((f0 acl2::any-p)))
  :xvar the-core-option-option)

;; SKIPPED trait/mixed declaration group (run with --monomorphize)

;; SKIPPED trait impl (run with --monomorphize)

;; SKIPPED trait/mixed declaration group (run with --monomorphize)

;; SKIPPED function core-slice-index-impl-core-slice-index-sliceindex-t-t-for-usize-index-mut: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function core-slice-index-impl-core-slice-index-sliceindex-t-t-for-usize-index: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function core-slice-index-impl-core-slice-index-sliceindex-t-t-for-usize-get-unchecked-mut: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function core-slice-index-impl-core-slice-index-sliceindex-t-t-for-usize-get-unchecked: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function core-slice-index-impl-core-slice-index-sliceindex-t-t-for-usize-get-mut: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function core-slice-index-impl-core-slice-index-sliceindex-t-t-for-usize-get: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED trait impl (run with --monomorphize)

;; SKIPPED function core-slice-t-len: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; unit struct alloc-alloc-global (values are (unit))

;; opaque type alloc-vec-vec (skipped)

;; SKIPPED function alloc-vec-alloc-vec-vec-t-len: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function alloc-vec-impl-core-ops-index-index-i-clause0-output-for-alloc-vec-vec-t-index: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function alloc-vec-impl-core-ops-index-indexmut-i-clause0-output-for-alloc-vec-vec-t-index-mut: ACL2: call to an opaque/std function with no ACL2 mapping yet

(defun loops-iter-loop0 (n max i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (< i max) (b* (((ok i) (u32-add i 1)))
  (loops-iter-loop0 n max i)) (ok i)))))

(defun loops-iter (n max)
  (loops-iter-loop0 n max 0))

(defun loops-sum-loop0 (n max i s)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (< i max) (b* (((ok s) (u32-add s i)))
  (b* (((ok i) (u32-add i 1)))
  (loops-sum-loop0 n max i s))) (ok s)))))

(defun loops-sum (n max)
  (b* (((ok s) (loops-sum-loop0 n max 0 0)))
  (u32-mul s 2)))

(defun loops-sum-with-mut-borrows-loop0 (n max i s)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (< i max) (b* (((ok ms) (u32-add s i)))
  (b* (((ok mi) (u32-add i 1)))
  (loops-sum-with-mut-borrows-loop0 n max mi ms))) (ok s)))))

(defun loops-sum-with-mut-borrows (n max)
  (b* (((ok s) (loops-sum-with-mut-borrows-loop0 n max 0 0)))
  (u32-mul s 2)))

(defun loops-sum-with-shared-borrows-loop0 (n max i s)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (< i max) (b* (((ok i) (u32-add i 1)))
  (b* (((ok s) (u32-add s i)))
  (loops-sum-with-shared-borrows-loop0 n max i s))) (ok s)))))

(defun loops-sum-with-shared-borrows (n max)
  (b* (((ok s) (loops-sum-with-shared-borrows-loop0 n max 0 0)))
  (u32-mul s 2)))

;; SKIPPED function loops-sum-array: ACL2: builtin (std) function not mapped in v0

;; SKIPPED function loops-sum-array: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-clear: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-clear: ACL2: call to a function that was itself skipped

(fty::deftagsum loops-list
  (:cons ((f0 acl2::any-p) (f1 loops-list-p)))
  (:nil ())
  :xvar the-loops-list)

(defun loops-list-mem-loop0 (n x ls)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp1 ls))
  (loops-list-case acl2tmp1
    :cons (b* ((y (loops-list-cons->f0 acl2tmp1)) (tl (loops-list-cons->f1 acl2tmp1))) (if (equal y x) (ok t) (loops-list-mem-loop0 n x tl)))
    :nil (ok nil))))))

(defun loops-list-mem (n x ls)
  (loops-list-mem-loop0 n x ls))

;; SKIPPED function loops-list-nth-mut: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED function loops-list-nth-mut: ACL2: call to a function that was itself skipped

(defun loops-list-nth-shared-loop0 (n ls i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp4 ls))
  (loops-list-case acl2tmp4
    :cons (b* ((x (loops-list-cons->f0 acl2tmp4)) (tl (loops-list-cons->f1 acl2tmp4))) (if (equal i 0) (ok x) (b* (((ok i) (u32-sub i 1)))
  (loops-list-nth-shared-loop0 n tl i))))
    :nil (fail (err-failure)))))))

(defun loops-list-nth-shared (n ls i)
  (loops-list-nth-shared-loop0 n ls i))

;; SKIPPED function loops-get-elem-mut: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED function loops-get-elem-mut: ACL2: call to a function that was itself skipped

(defun loops-get-elem-shared-loop0 (n x ls)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp7 ls))
  (loops-list-case acl2tmp7
    :cons (b* ((y (loops-list-cons->f0 acl2tmp7)) (tl (loops-list-cons->f1 acl2tmp7))) (if (equal y x) (ok y) (loops-get-elem-shared-loop0 n x tl)))
    :nil (fail (err-failure)))))))

;; SKIPPED function loops-get-elem-shared: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-id-mut: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

(defun loops-id-shared (ls)
  (ok ls))

;; SKIPPED function loops-list-nth-mut-with-id: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED function loops-list-nth-mut-with-id: ACL2: call to a function that was itself skipped

(defun loops-list-nth-shared-with-id-loop0 (n i ls)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp10 ls))
  (loops-list-case acl2tmp10
    :cons (b* ((x (loops-list-cons->f0 acl2tmp10)) (tl (loops-list-cons->f1 acl2tmp10))) (if (equal i 0) (ok x) (b* (((ok i) (u32-sub i 1)))
  (loops-list-nth-shared-with-id-loop0 n i tl))))
    :nil (fail (err-failure)))))))

(defun loops-list-nth-shared-with-id (n ls i)
  (b* (((ok ls) (loops-id-shared ls)))
  (loops-list-nth-shared-with-id-loop0 n i ls)))

;; SKIPPED function loops-list-nth-mut-pair: ACL2: destructuring let arity <> 2

;; SKIPPED function loops-list-nth-mut-pair: ACL2: call to a function that was itself skipped

(defun loops-list-nth-shared-pair-loop0 (n ls0 ls1 i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp14 ls0))
  (loops-list-case acl2tmp14
    :cons (b* ((x0 (loops-list-cons->f0 acl2tmp14)) (tl0 (loops-list-cons->f1 acl2tmp14))) (b* ((acl2tmp15 ls1))
  (loops-list-case acl2tmp15
    :cons (b* ((x1 (loops-list-cons->f0 acl2tmp15)) (tl1 (loops-list-cons->f1 acl2tmp15))) (if (equal i 0) (ok (cons x0 x1)) (b* (((ok i) (u32-sub i 1)))
  (loops-list-nth-shared-pair-loop0 n tl0 tl1 i))))
    :nil (fail (err-failure)))))
    :nil (fail (err-failure)))))))

(defun loops-list-nth-shared-pair (n ls0 ls1 i)
  (loops-list-nth-shared-pair-loop0 n ls0 ls1 i))

;; SKIPPED function loops-list-nth-mut-pair-merge: ACL2: destructuring let arity <> 2

;; SKIPPED function loops-list-nth-mut-pair-merge: ACL2: call to a function that was itself skipped

(defun loops-list-nth-shared-pair-merge-loop0 (n ls0 ls1 i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp19 ls0))
  (loops-list-case acl2tmp19
    :cons (b* ((x0 (loops-list-cons->f0 acl2tmp19)) (tl0 (loops-list-cons->f1 acl2tmp19))) (b* ((acl2tmp20 ls1))
  (loops-list-case acl2tmp20
    :cons (b* ((x1 (loops-list-cons->f0 acl2tmp20)) (tl1 (loops-list-cons->f1 acl2tmp20))) (if (equal i 0) (ok (cons x0 x1)) (b* (((ok i) (u32-sub i 1)))
  (loops-list-nth-shared-pair-merge-loop0 n tl0 tl1 i))))
    :nil (fail (err-failure)))))
    :nil (fail (err-failure)))))))

(defun loops-list-nth-shared-pair-merge (n ls0 ls1 i)
  (loops-list-nth-shared-pair-merge-loop0 n ls0 ls1 i))

;; SKIPPED function loops-list-nth-mut-shared-pair: ACL2: destructuring let arity <> 2

;; SKIPPED function loops-list-nth-mut-shared-pair: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-list-nth-mut-shared-pair-merge: ACL2: destructuring let arity <> 2

;; SKIPPED function loops-list-nth-mut-shared-pair-merge: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-list-nth-shared-mut-pair: ACL2: destructuring let arity <> 2

;; SKIPPED function loops-list-nth-shared-mut-pair: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-list-nth-shared-mut-pair-merge: ACL2: destructuring let arity <> 2

;; SKIPPED function loops-list-nth-shared-mut-pair-merge: ACL2: call to a function that was itself skipped

(defun loops-ignore-input-mut-borrow-loop0 (n i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (> i 0) (b* (((ok i) (u32-sub i 1)))
  (loops-ignore-input-mut-borrow-loop0 n i)) (ok (unit))))))

(defun loops-ignore-input-mut-borrow (n -a i)
  (b* (((ok &) (loops-ignore-input-mut-borrow-loop0 n i)))
  (ok -a)))

(defun loops-incr-ignore-input-mut-borrow-loop0 (n i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (> i 0) (b* (((ok i) (u32-sub i 1)))
  (loops-incr-ignore-input-mut-borrow-loop0 n i)) (ok (unit))))))

(defun loops-incr-ignore-input-mut-borrow (n a i)
  (b* (((ok a) (u32-add a 1)))
  (b* (((ok &) (loops-incr-ignore-input-mut-borrow-loop0 n i)))
  (ok a))))

(defun loops-ignore-input-shared-borrow-loop0 (n i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (> i 0) (b* (((ok i) (u32-sub i 1)))
  (loops-ignore-input-shared-borrow-loop0 n i)) (ok (unit))))))

(defun loops-ignore-input-shared-borrow (n -a i)
  (b* (((ok &) (loops-ignore-input-shared-borrow-loop0 n i)))
  (ok -a)))

(defun loops-issue500-1-bar (-a)
  (ok -a))

(defun loops-issue500-1-loop0 (n a)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (< 0 0) (b* (((ok a) (loops-issue500-1-bar a)))
  (loops-issue500-1-loop0 n a)) (ok a)))))

(defun loops-issue500-1 (n s)
  (loops-issue500-1-loop0 n s))

(defun loops-issue500-2-bar (-a)
  (ok -a))

(fty::defprod loops-issue500-2-a
  ((f0 acl2::any-p))
  :xvar the-loops-issue500-2-a)

(defun loops-issue500-2-loop0 (n)
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (ok (unit)))))

(defun loops-issue500-2 (n s)
  (b* (((ok &) (loops-issue500-2-loop0 n)))
  (ok s)))

(fty::defprod loops-issue500-3-a
  ((f0 acl2::any-p))
  :xvar the-loops-issue500-3-a)

(defun loops-issue500-3-loop0 (n)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (< 0 0) (loops-issue500-3-loop0 n) (ok (unit))))))

(defun loops-issue500-3 (n s)
  (b* (((ok &) (loops-issue500-3-loop0 n)))
  (ok s)))

(defun loops-issue351-loop0 (n t-var last)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp33 t-var))
  (loops-list-case acl2tmp33
    :cons (b* ((ht (loops-list-cons->f0 acl2tmp33)) (tt (loops-list-cons->f1 acl2tmp33))) (loops-issue351-loop0 n tt ht))
    :nil (ok last))))))

(defun loops-issue351 (n h t-var)
  (loops-issue351-loop0 n t-var h))

(defun loops-issue270-box-get-borrow (x)
  (ok x))

(defun loops-issue270-loop0 (n t-var last)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp34 t-var))
  (loops-list-case acl2tmp34
    :cons (b* ((ht (loops-list-cons->f0 acl2tmp34)) (tt (loops-list-cons->f1 acl2tmp34))) (b* (((ok t-var) (loops-issue270-box-get-borrow tt)))
  (loops-issue270-loop0 n t-var ht)))
    :nil (ok last))))))

(defun loops-issue270 (n v)
  (b* ((acl2tmp35 v))
  (loops-list-case acl2tmp35
    :cons (b* ((h (loops-list-cons->f0 acl2tmp35)) (t-var (loops-list-cons->f1 acl2tmp35))) (b* (((ok t-var) (loops-issue270-box-get-borrow t-var)))
  (b* (((ok last) (loops-issue270-loop0 n t-var h)))
  (ok (core-option-option-some last)))))
    :nil (ok (core-option-option-none)))))

;; SKIPPED function loops-issue400-1: ACL2: application of a function-typed variable (HO)

;; SKIPPED function loops-issue400-1: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED function loops-issue400-2: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-issue400-2: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED global (not supported in v0)

;; SKIPPED function loops-copy-carray: ACL2: globals not supported in v0

;; SKIPPED function loops-copy-carray: ACL2: call to a function that was itself skipped

(defun loops-iter-local-mut-borrow-loop0 (n p)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* (((ok p) (i32-add p 1)))
  (if (equal p 10) (ok (unit)) (loops-iter-local-mut-borrow-loop0 n p))))))

(defun loops-iter-local-mut-borrow (n)
  (loops-iter-local-mut-borrow-loop0 n 0))

(defun loops-iter-local-shared-borrow-loop0 (n)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (equal 0 0) (ok (unit)) (loops-iter-local-shared-borrow-loop0 n)))))

(defun loops-iter-local-shared-borrow (n)
  (loops-iter-local-shared-borrow-loop0 n))

(fty::deftagsum loops-alist
  (:cons ((f0 acl2::any-p) (f1 acl2::any-p) (f2 loops-alist-p)))
  (:nil ())
  :xvar the-loops-alist)

(defun loops-insert-in-list-loop0 (n key value ls)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp36 ls))
  (loops-alist-case acl2tmp36
    :cons (b* ((ckey (loops-alist-cons->f0 acl2tmp36)) (cvalue (loops-alist-cons->f1 acl2tmp36)) (tl (loops-alist-cons->f2 acl2tmp36))) (if (equal ckey key) (ok (cons nil (loops-alist-cons ckey value tl))) (b* (((ok v0) (loops-insert-in-list-loop0 n key value tl)))
  (b* ((acl2tmp37 v0)
     (v0 (car acl2tmp37))
     (back (cdr acl2tmp37)))
  (b* ((back (loops-alist-cons ckey cvalue back)))
  (ok (cons v0 back)))))))
    :nil (ok (cons t (loops-alist-cons key value (loops-alist-nil)))))))))

(defun loops-insert-in-list (n key value ls)
  (loops-insert-in-list-loop0 n key value ls))

(defun loops-reborrow-const-reborrow (x)
  (ok x))

(defun loops-reborrow-const-loop0 (n)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (< 0 5) (b* (((ok &) (loops-reborrow-const-reborrow 0)))
  (loops-reborrow-const-loop0 n)) (ok (unit))))))

(defun loops-reborrow-const (n)
  (loops-reborrow-const-loop0 n))

(defun loops-decode-loop1 (n dst-coeff)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (if (> dst-coeff 32) (loops-decode-loop1 n dst-coeff) (ok (unit))))))

;; SKIPPED function loops-decode: ACL2: builtin (std) function not mapped in v0

;; SKIPPED function loops-decode: ACL2: call to a function that was itself skipped

;; SKIPPED function loops-as-radix-minimized: ACL2: builtin (std) function not mapped in v0

;; SKIPPED function loops-as-radix-minimized: ACL2: builtin (std) function not mapped in v0

;; SKIPPED function loops-single-break: ACL2: builtin (std) function not mapped in v0

;; SKIPPED function loops-single-break: ACL2: call to a function that was itself skipped

;; END OF GENERATED FILE
