;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [range_both]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

(fty::deftagsum core-option-option-i32-
  (:none ())
  (:some ((f0 acl2::any-p)))
  :xvar the-core-option-option-i32-)

(fty::defprod core-ops-range-range-i32-
  ((start acl2::any-p) (end acl2::any-p))
  :xvar the-core-ops-range-range-i32-)

(defun core-iter-range-impl-core-iter-traits-iterator-iterator-for-core-ops-range-range-i32-next-i32- (self)
  (b* ((s (core-ops-range-range-i32-->start self))
       (e (core-ops-range-range-i32-->end self)))
  (if (< s e)
      (ok (cons (core-option-option-i32--some s) (core-ops-range-range-i32- (+ s 1) e)))
    (ok (cons (core-option-option-i32--none) self)))))

(fty::deftagsum core-option-option-usize-
  (:none ())
  (:some ((f0 acl2::any-p)))
  :xvar the-core-option-option-usize-)

(fty::defprod core-ops-range-range-usize-
  ((start acl2::any-p) (end acl2::any-p))
  :xvar the-core-ops-range-range-usize-)

(defun core-iter-range-impl-core-iter-traits-iterator-iterator-for-core-ops-range-range-usize-next-usize- (self)
  (b* ((s (core-ops-range-range-usize-->start self))
       (e (core-ops-range-range-usize-->end self)))
  (if (< s e)
      (ok (cons (core-option-option-usize--some s) (core-ops-range-range-usize- (+ s 1) e)))
    (ok (cons (core-option-option-usize--none) self)))))

(defun core-iter-traits-collect-impl-core-iter-traits-collect-intoiterator-for-core-ops-range-range-usize-into-iter-core-ops-range-range-usize- (self) (ok self))

(defun core-iter-traits-collect-impl-core-iter-traits-collect-intoiterator-for-core-ops-range-range-i32-into-iter-core-ops-range-range-i32- (self) (ok self))

(defun range-both-sum-usize-loop0 (n iter a acc)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_1 (1- n)))
  (b* (((ok v2_2) (core-iter-range-impl-core-iter-traits-iterator-iterator-for-core-ops-range-range-usize-next-usize- iter)))
  (b* ((acl2tmp3 v2_2)
     (v4_4 (car acl2tmp3))
     (iter_5 (cdr acl2tmp3)))
  (b* ((acl2tmp6 v4_4))
  (core-option-option-usize--case acl2tmp6
    :none (ok acc)
    :some (b* ((i_7 (core-option-option-usize--some->f0 acl2tmp6))) (b* (((ok v8_8) (array-index a i_7)))
  (b* (((ok acc_9) (u32-wrapping-add acc v8_8)))
  (range-both-sum-usize-loop0 n_1 iter_5 a acc_9)))))))))))

(defun range-both-sum-usize (n a)
  (b* (((ok iter_10) (core-iter-traits-collect-impl-core-iter-traits-collect-intoiterator-for-core-ops-range-range-usize-into-iter-core-ops-range-range-usize- (make-core-ops-range-range-usize- :start 0 :end 4))))
  (range-both-sum-usize-loop0 n iter_10 a 0)))

(defun range-both-count-i32-loop0 (n iter acc)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_11 (1- n)))
  (b* (((ok v12_12) (core-iter-range-impl-core-iter-traits-iterator-iterator-for-core-ops-range-range-i32-next-i32- iter)))
  (b* ((acl2tmp13 v12_12)
     (v14_14 (car acl2tmp13))
     (iter_15 (cdr acl2tmp13)))
  (b* ((acl2tmp16 v14_14))
  (core-option-option-i32--case acl2tmp16
    :none (ok acc)
    :some (b* ((j_17 (core-option-option-i32--some->f0 acl2tmp16))) (b* (((ok acc_18) (i32-add acc j_17)))
  (range-both-count-i32-loop0 n_11 iter_15 acc_18))))))))))

(defun range-both-count-i32 (n)
  (b* (((ok iter_19) (core-iter-traits-collect-impl-core-iter-traits-collect-intoiterator-for-core-ops-range-range-i32-into-iter-core-ops-range-range-i32- (make-core-ops-range-range-i32- :start 1 :end 5))))
  (range-both-count-i32-loop0 n iter_19 0)))

;; END OF GENERATED FILE
