;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [rev_range]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

;; opaque type core-iter-adapters-rev-rev-core-ops-range-range-usize- (skipped)

(fty::deftagsum core-option-option-usize-
  (:none ())
  (:some ((f0 acl2::any-p)))
  :xvar the-core-option-option-usize-)

;; SKIPPED function core-iter-adapters-rev-impl-core-iter-traits-iterator-iterator-for-core-iter-adapters-rev-rev-core-ops-range-range-usize-next-core-ops-range-range-usize-: ACL2: call to an opaque/std function with no ACL2 mapping yet

(defun core-iter-traits-collect-impl-core-iter-traits-collect-intoiterator-for-core-iter-adapters-rev-rev-core-ops-range-range-usize-into-iter-core-iter-adapters-rev-rev-core-ops-range-range-usize- (self) (ok self))

;; SKIPPED trait/mixed declaration group (run with --monomorphize)

(fty::defprod core-ops-range-range-usize-
  ((start acl2::any-p) (end acl2::any-p))
  :xvar the-core-ops-range-range-usize-)

;; SKIPPED function core-iter-traits-iterator-iterator-rev-core-ops-range-range-usize-: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; SKIPPED function rev-range-sum-rev: ACL2: call to a function that was itself skipped

;; SKIPPED function rev-range-sum-rev: ACL2: call to a function that was itself skipped

;; SKIPPED function rev-range-shift-up: ACL2: call to a function that was itself skipped

;; SKIPPED function rev-range-shift-up: ACL2: call to a function that was itself skipped

;; END OF GENERATED FILE
