(in-package "ACL2")
(include-book "aes_fixslice_cipher")
(defthm pfx-2
  (implies (and (true-listp s0) (equal (len s0) 8)
                (true-listp rk) (equal (len rk) 88))
           (equal (result-kind (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-2 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-1 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 s0 rk 0)))))) rk 8)))))) rk 16)) :ok))
  :hints (("Goal" :do-not-induct t
           :in-theory (union-theories (theory 'ground-zero)
                        '((:definition not)
                          (:rewrite result-kind-of-sub-bytes-len)
                          (:rewrite len-of-sub-bytes-len)
                          (:rewrite true-listp-of-sub-bytes-len)
                          (:rewrite result-kind-of-mc0-len) (:rewrite len-of-mc0-len) (:rewrite true-listp-of-mc0-len)
                          (:rewrite result-kind-of-mc1-len) (:rewrite len-of-mc1-len) (:rewrite true-listp-of-mc1-len)
                          (:rewrite result-kind-of-mc2-len) (:rewrite len-of-mc2-len) (:rewrite true-listp-of-mc2-len)
                          (:rewrite result-kind-of-mc3-len) (:rewrite len-of-mc3-len) (:rewrite true-listp-of-mc3-len)
                          (:rewrite ark-form100)
                          (:rewrite len-of-arkw-spec) (:rewrite true-listp-of-arkw-spec)
                          (:rewrite result-ok->val-of-result-ok)
                          (:rewrite rk-of-ok2)
                          (:executable-counterpart nfix) (:executable-counterpart zp)
                          (:executable-counterpart binary-+) (:executable-counterpart binary-*)
                          (:executable-counterpart <) (:executable-counterpart unary--)
                          (:executable-counterpart natp) (:executable-counterpart integerp)
                          (:executable-counterpart equal) (:executable-counterpart eq)))))
  :rule-classes nil)
(defthm pfx-3
  (implies (and (true-listp s0) (equal (len s0) 8)
                (true-listp rk) (equal (len rk) 88))
           (equal (result-kind (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-3 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-2 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-1 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 s0 rk 0)))))) rk 8)))))) rk 16)))))) rk 24)) :ok))
  :hints (("Goal" :do-not-induct t
           :in-theory (union-theories (theory 'ground-zero)
                        '((:definition not)
                          (:rewrite result-kind-of-sub-bytes-len)
                          (:rewrite len-of-sub-bytes-len)
                          (:rewrite true-listp-of-sub-bytes-len)
                          (:rewrite result-kind-of-mc0-len) (:rewrite len-of-mc0-len) (:rewrite true-listp-of-mc0-len)
                          (:rewrite result-kind-of-mc1-len) (:rewrite len-of-mc1-len) (:rewrite true-listp-of-mc1-len)
                          (:rewrite result-kind-of-mc2-len) (:rewrite len-of-mc2-len) (:rewrite true-listp-of-mc2-len)
                          (:rewrite result-kind-of-mc3-len) (:rewrite len-of-mc3-len) (:rewrite true-listp-of-mc3-len)
                          (:rewrite ark-form100)
                          (:rewrite len-of-arkw-spec) (:rewrite true-listp-of-arkw-spec)
                          (:rewrite result-ok->val-of-result-ok)
                          (:rewrite rk-of-ok2)
                          (:executable-counterpart nfix) (:executable-counterpart zp)
                          (:executable-counterpart binary-+) (:executable-counterpart binary-*)
                          (:executable-counterpart <) (:executable-counterpart unary--)
                          (:executable-counterpart natp) (:executable-counterpart integerp)
                          (:executable-counterpart equal) (:executable-counterpart eq)))))
  :rule-classes nil)
(defthm pfx-4
  (implies (and (true-listp s0) (equal (len s0) 8)
                (true-listp rk) (equal (len rk) 88))
           (equal (result-kind (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-0 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-3 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-2 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-1 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 s0 rk 0)))))) rk 8)))))) rk 16)))))) rk 24)))))) rk 32)) :ok))
  :hints (("Goal" :do-not-induct t
           :in-theory (union-theories (theory 'ground-zero)
                        '((:definition not)
                          (:rewrite result-kind-of-sub-bytes-len)
                          (:rewrite len-of-sub-bytes-len)
                          (:rewrite true-listp-of-sub-bytes-len)
                          (:rewrite result-kind-of-mc0-len) (:rewrite len-of-mc0-len) (:rewrite true-listp-of-mc0-len)
                          (:rewrite result-kind-of-mc1-len) (:rewrite len-of-mc1-len) (:rewrite true-listp-of-mc1-len)
                          (:rewrite result-kind-of-mc2-len) (:rewrite len-of-mc2-len) (:rewrite true-listp-of-mc2-len)
                          (:rewrite result-kind-of-mc3-len) (:rewrite len-of-mc3-len) (:rewrite true-listp-of-mc3-len)
                          (:rewrite ark-form100)
                          (:rewrite len-of-arkw-spec) (:rewrite true-listp-of-arkw-spec)
                          (:rewrite result-ok->val-of-result-ok)
                          (:rewrite rk-of-ok2)
                          (:executable-counterpart nfix) (:executable-counterpart zp)
                          (:executable-counterpart binary-+) (:executable-counterpart binary-*)
                          (:executable-counterpart <) (:executable-counterpart unary--)
                          (:executable-counterpart natp) (:executable-counterpart integerp)
                          (:executable-counterpart equal) (:executable-counterpart eq)))))
  :rule-classes nil)
(defthm pfx-5
  (implies (and (true-listp s0) (equal (len s0) 8)
                (true-listp rk) (equal (len rk) 88))
           (equal (result-kind (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-1 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-0 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-3 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-2 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 (result-ok->val (aes-fixslice-encrypt-mix-columns-1 (result-ok->val (aes-fixslice-encrypt-sub-bytes (result-ok->val (aes-fixslice-encrypt-add-round-key 100 s0 rk 0)))))) rk 8)))))) rk 16)))))) rk 24)))))) rk 32)))))) rk 40)) :ok))
  :hints (("Goal" :do-not-induct t
           :in-theory (union-theories (theory 'ground-zero)
                        '((:definition not)
                          (:rewrite result-kind-of-sub-bytes-len)
                          (:rewrite len-of-sub-bytes-len)
                          (:rewrite true-listp-of-sub-bytes-len)
                          (:rewrite result-kind-of-mc0-len) (:rewrite len-of-mc0-len) (:rewrite true-listp-of-mc0-len)
                          (:rewrite result-kind-of-mc1-len) (:rewrite len-of-mc1-len) (:rewrite true-listp-of-mc1-len)
                          (:rewrite result-kind-of-mc2-len) (:rewrite len-of-mc2-len) (:rewrite true-listp-of-mc2-len)
                          (:rewrite result-kind-of-mc3-len) (:rewrite len-of-mc3-len) (:rewrite true-listp-of-mc3-len)
                          (:rewrite ark-form100)
                          (:rewrite len-of-arkw-spec) (:rewrite true-listp-of-arkw-spec)
                          (:rewrite result-ok->val-of-result-ok)
                          (:rewrite rk-of-ok2)
                          (:executable-counterpart nfix) (:executable-counterpart zp)
                          (:executable-counterpart binary-+) (:executable-counterpart binary-*)
                          (:executable-counterpart <) (:executable-counterpart unary--)
                          (:executable-counterpart natp) (:executable-counterpart integerp)
                          (:executable-counterpart equal) (:executable-counterpart eq)))))
  :rule-classes nil)
