;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [vec_sum]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

;; opaque type alloc-vec-vec-u32- (skipped)

(defun vec-sum-sum-loop0 (n v s i)
  (declare (xargs :measure (nfix n)
                  :hints (("Goal" :in-theory (theory 'ground-zero)))))
  (if (zp n) (result-fail (err-out-of-fuel)) (b* ((n_1 (1- n)))
  (b* (((ok v2_2) (vec-len v)))
  (if (< i v2_2) (b* (((ok v3_3) (array-index v i)))
  (b* (((ok s_4) (u32-wrapping-add s v3_3)))
  (b* (((ok i_5) (usize-add i 1)))
  (vec-sum-sum-loop0 n_1 v s_4 i_5)))) (ok s))))))

(defun vec-sum-sum (n v)
  (vec-sum-sum-loop0 n v 0 0))

;; SKIPPED function vec-sum-double-first: ACL2: application of a function-typed variable (HO)

;; END OF GENERATED FILE
