;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [vec_demo]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

;; opaque type alloc-vec-vec-u32- (skipped)

(defun vec-demo-build-pair (a b)
  (b* (((ok v_1) (vec-new)))
  (b* (((ok v_2) (vec-push v_1 a)))
  (vec-push v_2 b))))

(defun vec-demo-get0 (v)
  (array-index v 0))

(defun vec-demo-len-of (v)
  (vec-len v))

;; END OF GENERATED FILE
