;; THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
;; [no_nested_borrows]
(in-package "ACL2")

(include-book "rust-primitives")

(set-ignore-ok t)
(set-irrelevant-formals-ok t)

;; SKIPPED function core-mem-replace: ACL2: call to an opaque/std function with no ACL2 mapping yet

;; unit struct alloc-alloc-global (values are (unit))

(fty::defprod no-nested-borrows-pair
  ((x acl2::any-p) (y acl2::any-p))
  :xvar the-no-nested-borrows-pair)

(fty::deftagsum no-nested-borrows-list
  (:cons ((f0 acl2::any-p) (f1 acl2::any-p)))
  (:nil ())
  :xvar the-no-nested-borrows-list)

(fty::deftagsum no-nested-borrows-one
  (:one ((f0 acl2::any-p)))
  :xvar the-no-nested-borrows-one)

(fty::deftagsum no-nested-borrows-emptyenum
  (:empty ())
  :xvar the-no-nested-borrows-emptyenum)

(fty::deftagsum no-nested-borrows-enum
  (:variant1 ())
  (:variant2 ())
  :xvar the-no-nested-borrows-enum)

;; unit struct no-nested-borrows-emptystruct (values are (unit))

(fty::deftagsum no-nested-borrows-sum
  (:left ((f0 acl2::any-p)))
  (:right ((f0 acl2::any-p)))
  :xvar the-no-nested-borrows-sum)

;; SKIPPED function no-nested-borrows-cast-u32-to-i32: ACL2: unsupported unop (neg/cast)

;; SKIPPED function no-nested-borrows-cast-bool-to-i32: ACL2: unsupported unop (neg/cast)

(defun no-nested-borrows-cast-bool-to-bool (x)
  (ok x))

(defun no-nested-borrows-test2 ()
  (b* (((ok &) (u32-add 23 44)))
  (ok (unit))))

(defun no-nested-borrows-get-max (x y)
  (if (>= x y) (ok x) (ok y)))

(defun no-nested-borrows-test3 ()
  (b* (((ok x) (no-nested-borrows-get-max 4 3)))
  (b* (((ok y) (no-nested-borrows-get-max 10 11)))
  (b* (((ok z) (u32-add x y)))
  (massert (equal z 15))))))

;; SKIPPED function no-nested-borrows-test-neg1: ACL2: unsupported unop (neg/cast)

(defun no-nested-borrows-refs-test1 ()
  (massert (equal 1 1)))

(defun no-nested-borrows-refs-test2 ()
  (b* (((ok &) (massert (equal 2 2))))
  (b* (((ok &) (massert (equal 0 0))))
  (b* (((ok &) (massert (equal 2 2))))
  (massert (equal 2 2))))))

(defun no-nested-borrows-test-list1 ()
  (ok (unit)))

(defun no-nested-borrows-copy-int (x)
  (ok x))

(defun no-nested-borrows-test-unreachable (b)
  (massert (not b)))

(defun no-nested-borrows-test-panic (b)
  (massert (not b)))

(defun no-nested-borrows-test-panic-msg (b)
  (massert (not b)))

(defun no-nested-borrows-test-copy-int ()
  (b* (((ok y) (no-nested-borrows-copy-int 0)))
  (massert (equal 0 y))))

(defun no-nested-borrows-is-cons (l)
  (b* ((acl2tmp1 l))
  (no-nested-borrows-list-case acl2tmp1
    :cons (ok t)
    :nil (ok nil))))

(defun no-nested-borrows-test-is-cons ()
  (b* (((ok v0) (no-nested-borrows-is-cons (no-nested-borrows-list-cons 0 (no-nested-borrows-list-nil)))))
  (massert v0)))

(defun no-nested-borrows-split-list (l)
  (b* ((acl2tmp2 l))
  (no-nested-borrows-list-case acl2tmp2
    :cons (b* ((hd (no-nested-borrows-list-cons->f0 acl2tmp2)) (tl (no-nested-borrows-list-cons->f1 acl2tmp2))) (ok (cons hd tl)))
    :nil (fail (err-failure)))))

(defun no-nested-borrows-test-split-list ()
  (b* (((ok v0) (no-nested-borrows-split-list (no-nested-borrows-list-cons 0 (no-nested-borrows-list-nil)))))
  (b* ((acl2tmp3 v0)
     (hd (car acl2tmp3)))
  (massert (equal hd 0)))))

;; SKIPPED function no-nested-borrows-choose: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED function no-nested-borrows-choose-test: ACL2: call to a function that was itself skipped

;; SKIPPED function no-nested-borrows-test-char: ACL2: unsupported literal (char/str/float)

(defun no-nested-borrows-panic-mut-borrow (v0)
  (fail (err-failure)))

;; SKIPPED mutually recursive type group

(defun no-nested-borrows-list-length (n l)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp4 l))
  (no-nested-borrows-list-case acl2tmp4
    :cons (b* ((l1 (no-nested-borrows-list-cons->f1 acl2tmp4))) (b* (((ok v0) (no-nested-borrows-list-length n l1)))
  (u32-add 1 v0)))
    :nil (ok 0))))))

(defun no-nested-borrows-list-nth-shared (n l i)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp5 l))
  (no-nested-borrows-list-case acl2tmp5
    :cons (b* ((x (no-nested-borrows-list-cons->f0 acl2tmp5)) (tl (no-nested-borrows-list-cons->f1 acl2tmp5))) (if (equal i 0) (ok x) (b* (((ok v0) (u32-sub i 1)))
  (no-nested-borrows-list-nth-shared n tl v0))))
    :nil (fail (err-failure)))))))

;; SKIPPED function no-nested-borrows-list-nth-mut: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

(defun no-nested-borrows-list-rev-aux (n li lo)
  (declare (xargs :measure (nfix n)))
  (if (zp n) (fail (err-out-of-fuel)) (b* ((n (1- n)))
  (b* ((acl2tmp8 li))
  (no-nested-borrows-list-case acl2tmp8
    :cons (b* ((hd (no-nested-borrows-list-cons->f0 acl2tmp8)) (tl (no-nested-borrows-list-cons->f1 acl2tmp8))) (no-nested-borrows-list-rev-aux n tl (no-nested-borrows-list-cons hd lo)))
    :nil (ok lo))))))

;; SKIPPED function no-nested-borrows-list-rev: ACL2: call to a function that was itself skipped

;; SKIPPED function no-nested-borrows-test-list-functions: ACL2: call to a function that was itself skipped

;; SKIPPED function no-nested-borrows-id-mut-pair1: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED function no-nested-borrows-id-mut-pair2: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED function no-nested-borrows-id-mut-pair3: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

;; SKIPPED function no-nested-borrows-id-mut-pair4: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

(fty::defprod no-nested-borrows-structwithtuple
  ((p acl2::any-p))
  :xvar the-no-nested-borrows-structwithtuple)

;; SKIPPED function no-nested-borrows-new-tuple1: ACL2: struct update not supported in v0

;; SKIPPED function no-nested-borrows-new-tuple2: ACL2: struct update not supported in v0

;; SKIPPED function no-nested-borrows-new-tuple3: ACL2: struct update not supported in v0

(fty::defprod no-nested-borrows-structwithpair
  ((p acl2::any-p))
  :xvar the-no-nested-borrows-structwithpair)

;; SKIPPED function no-nested-borrows-new-pair1: ACL2: struct update not supported in v0

;; SKIPPED function no-nested-borrows-test-constants: ACL2: call to a function that was itself skipped

(defun no-nested-borrows-test-weird-borrows1 ()
  (ok (unit)))

;; SKIPPED function no-nested-borrows-test-mem-replace: ACL2: call to a function that was itself skipped

(defun no-nested-borrows-test-shared-borrow-bool1 (b)
  (if b (ok 0) (ok 1)))

(defun no-nested-borrows-test-shared-borrow-bool2 ()
  (ok 0))

(defun no-nested-borrows-test-shared-borrow-enum1 (l)
  (b* ((acl2tmp9 l))
  (no-nested-borrows-list-case acl2tmp9
    :cons (ok 1)
    :nil (ok 0))))

(defun no-nested-borrows-test-shared-borrow-enum2 ()
  (ok 0))

(defun no-nested-borrows-incr (x)
  (u32-add x 1))

(defun no-nested-borrows-call-incr (x)
  (no-nested-borrows-incr x))

(defun no-nested-borrows-read-then-incr (x)
  (b* (((ok x) (u32-add x 1)))
  (ok (cons x x))))

(fty::defprod no-nested-borrows-tuple
  ((f0 acl2::any-p) (f1 acl2::any-p))
  :xvar the-no-nested-borrows-tuple)

(defun no-nested-borrows-read-tuple (x)
  (b* ((acl2tmp10 x)
     (v0 (car acl2tmp10)))
  (ok v0)))

(defun no-nested-borrows-update-tuple (x)
  (b* ((acl2tmp11 x)
     (v0 (cdr acl2tmp11)))
  (ok (cons 1 v0))))

(defun no-nested-borrows-read-tuple-struct (x)
  (b* ((acl2tmp12 x)
     (v0 (car acl2tmp12)))
  (ok v0)))

(defun no-nested-borrows-update-tuple-struct (x)
  (b* ((acl2tmp13 x)
     (v0 (cdr acl2tmp13)))
  (ok (no-nested-borrows-tuple 1 v0))))

(defun no-nested-borrows-create-tuple-struct (x y)
  (ok (no-nested-borrows-tuple x y)))

(fty::defprod no-nested-borrows-idtype
  ((f0 acl2::any-p))
  :xvar the-no-nested-borrows-idtype)

(defun no-nested-borrows-use-id-type (x)
  (ok x))

(defun no-nested-borrows-create-id-type (x)
  (ok (no-nested-borrows-idtype x)))

(defun no-nested-borrows-not-bool (x)
  (ok (not x)))

;; SKIPPED function no-nested-borrows-not-u32: ACL2: unsupported unop (neg/cast)

;; SKIPPED function no-nested-borrows-not-i32: ACL2: unsupported unop (neg/cast)

;; SKIPPED function no-nested-borrows-borrow-mut-tuple: ACL2: lambda in output (backward function or closure); not supported in v0 -- see the defunctionalization plan

(fty::defprod no-nested-borrows-expandsimpliy-wrapper
  ((f0 acl2::any-p) (f1 acl2::any-p))
  :xvar the-no-nested-borrows-expandsimpliy-wrapper)

(defun no-nested-borrows-expandsimpliy-check-expand-simplify-symb1 (x)
  (b* ((acl2tmp14 x)
     (v0 (car acl2tmp14)))
  (if v0 (ok x) (ok x))))

(fty::defprod no-nested-borrows-expandsimpliy-wrapper2
  ((b acl2::any-p) (x acl2::any-p))
  :xvar the-no-nested-borrows-expandsimpliy-wrapper2)

(defun no-nested-borrows-expandsimpliy-check-expand-simplify-symb2 (x)
  (if (no-nested-borrows-expandsimpliy-wrapper2->b x) (ok x) (ok x)))

;; END OF GENERATED FILE
